### ISSUE TITLE
SP world crash with CCL

### ISSUE THREAD

**Issue by otsns** [DeadlyMC/ForgedCarpet112#2]
Game crashes when i trying to load the singleplayer world with codechickenlib installed. 
Only thing i can do is try to change mod versions(
tested with:
ForgedCarpet v1.0.0
1.12.2-forge1.12.2-14.23.5.2796
1.12.2-forge1.12.2-14.23.5.2811
CodeChickenLib-1.12.2-3.2.2.354-universal latest
CodeChickenLib-1.12.2-3.2.2.353-universal recommended

singleplayer crash report https://pastebin.com/raw/YR1qszjV

**Comment by DeadlyMC** [comment]
Thanks for the report! I'll look into the issue

**Comment by DeadlyMC** [comment]
This seems to have been fixed in commit [07cf9c9abad14064e14f77a8905c68c812d64f96](https://github.com/DeadlyMC/ForgedCarpet112/commit/07cf9c9abad14064e14f77a8905c68c812d64f96#diff-b0dc6e00962e9b2df6758c6c78a747c5)

So this should be fixed in next release
Please leave this issue open until u confirm that it works

**Comment by DeadlyMC** [comment]
Please try out v1.1.0 and confirm if it works so that i can close this issue

**Comment by otsns** [comment]
i dont even know... cant confirm that since i got crash with carpetmod itself! Super clean minecraft, no other mods, new world (singleplayer ofc) forge only, wiped settings and it still crashes the game with world loading.

debug.log        https://pastebin.com/raw/SxF25dvd
crash report     https://pastebin.com/raw/EW13bV0g
latest.log          https://pastebin.com/raw/59Zk9yiF
this is probably my problem but i cant uderstand why. Ican also upload log files.

**Comment by DeadlyMC** [comment]
It actually isn't your problem. It seems like i messed up something when making my mod not crash with liteloader, so now it works with liteloader+ forge but doesn't with forge only xD

I'm working on a fix right now

**Comment by DeadlyMC** [comment]
U can maybe use liteloader + forge profile until then

**Comment by otsns** [comment]
ok waiting for newest version. I will notice you when i try it! Also thanks for curseforge upload!

**Comment by DeadlyMC** [comment]
Please try out v1.1.1 and confirm whether it works for you....should be hopefully fixed now

**Comment by otsns** [comment]
Yes, working fine!

**Comment by DeadlyMC** [comment]
Great! Once again thanks for the report! It really helps me out
